config/routes.rb
Rails.application.routes.draw do
  root controller: :articles, action: :index  
  resources :articles, only: [:show, :new, :create, :edit, :update] # get a single item, get a list of item is index action
  # new= show form, create= create in db
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :id, :title, :content #telling our model that it has to validate every article we try to save has a title before sending to db
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all #goes and gets all articles from db. After it is fetched it should send it to views to disply them
  end
  
  def show
    @article = Article.find(params[:id]) 
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params) 
    
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])     
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated' #if updated redirected back to article + message
    else
      redirect_to edit_article_path, notice: 'Something went wrong, try again' # other stay andshow error message
    end
  end

  private

  def article_params # only allow title and content. Nothing is ok
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/edit.html.erb
<br>
<br>
<%= form_with  model: @article, local: true do |form| %>
  <strong><%= form.label :title%></strong>
  <%= form.text_field :title %>
  <strong><%= form.label :content %></strong>
  <%= form.text_area :content %>
  <br>
  <br>
  <%= form.submit 'Update Article'%>
<% end %>
<br>
<%= link_to 'Back Article List', root_path %>

app/views/articles/index.html.erb
<ul>
  <% @articles.each do |article| %> 
    <h1><%= link_to article.title, article_path(article) %></h1>
      <li>
        <%= article.title %><br />
      </li>
  <% end %>
</ul>
  <%= link_to "Write an Article", new_article_path%>

app/views/articles/new.html.erb
<%= form_with model: @article, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %><br>
  <%= form.label :content %>
  <%= form.text_area :content %><br><br>
  <%= form.submit 'Create Article' %>
<% end %>
<br>
<%= link_to 'Back To Article List', root_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
<br> 
<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<ul>
  <li><%= link_to 'Back To Article List', root_path %></li>
  <li><%= link_to 'Edit this Article', edit_article_path(@article) %></li>
</ul> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>